### ISSUE TITLE
Wrong Path in rtd-start

### ISSUE THREAD

**Issue by dklesev** [moul/docker-readthedocs#1]
I've tried with pulling the image from index and by building one myself I get the same error:

```
dev@ubuntu:~/docker-readthedocs$ sudo docker run -p 127.0.0.1:54545:8000 readthedocs:latest /bin/sh -e /bin/rtd-start.sh
-su: line 0: cd: /home/py/app: No such file or directory
-su: /home/py/venv/bin/python: No such file or directory
```

Path in rtd-start seems to be wrong

**Comment by luebken** [comment]
+1

**Comment by fbertux** [comment]
Hi!
I can't build the image. This  error appears:

``` shell
/venv/bin/python: can't open file 'manage.py': [Errno 2] No such file or directory
2014/12/11 14:57:55 The command [/bin/sh -c /bin/rtd-install.sh] returned a non-zero code: 2
```

I tried change the path on rtd-install.sh but doesn't work. How do I fix this issue?

**Comment by moul** [comment]
Just updated the [README.md](https://github.com/moul/docker-readthedocs/blob/master/README.md) file with working instructions

From what I can see, the run works fine, but the rebuild fails, I need to check out what changed since the last time it worked
