### ISSUE TITLE
config question

### ISSUE THREAD

**Issue by carukc** [moul/docker-readthedocs#3]
Hello,

I've been looking at your image and have a question.  In the Dockerfile you copy: config to: /

and set ENV DJANGO_SETTINGS_MODULE config .

When I try to build from scratch I get : 

ImportError: Could not import settings 'config' (Is it on sys.path? Is there an import error in the settings file?): No module named config

Strangely your image (on the docker hub), does not have the /config directory in / but still has the DJANGO_SETTINGS_MODULE=config environment variable set.

Am I missing something or did you later delete the /config directory?

Thanks
Chris

**Comment by carukc** [comment]
never mind... my bad.  I see that you are copying these files into /etc and /bin.

Thanks
Chris

**Comment by moul** [comment]
no problem :)
